example:
  service:
    prefix: jkdjskjf
    suffix: jjkjkj
    enabled: true
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
  datasource:
    url: jdbc:h2:file:./db/test_001 # 文件形式的配置
    username: sa
    password: 123456
    platform: h2
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

#    url: jdbc:h2:mem:test  内存性质的配置